version: '3'
services:
  v2ray:
    container_name: v2ray
    image: v2fly/v2fly-core
    command: run -c /etc/v2ray/config.json
    restart: always
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    ports:
      - "127.0.0.1:10000:10000"
    volumes:
      - "./v2ray:/etc/v2ray"
  caddy:
    container_name: caddy
    image: caddy
    restart: always
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
      WEBSITE_HOSTNAME: mydomain.com
    network_mode: "host"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - ".caddy:/data/caddy"
