# fly.toml app configuration file generated for ws-connliu on 2023-05-13T07:01:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ws-connliu"
primary_region = "hkg"

[build]
  image = "liuxingjun/v2ray:nginx"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
