name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
     - '.github/**'
     - 'Dockerfile'
     - 'config.json'
     - 'default.conf'
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push caddy
        uses: docker/build-push-action@v4
        with:
          target: "caddy"
          push: true
          tags: liuxingjun/v2ray:caddy
      - name: Build and push nginx
        uses: docker/build-push-action@v4
        with:
          target: "nginx"
          push: true
          tags: liuxingjun/v2ray:nginx
      - name: Build and push azure
        uses: docker/build-push-action@v4
        with:
          target: "azure"
          push: true
          tags: liuxingjun/v2ray:azure